version : '3.9'


services:

  php5.6:
    build: .
    container_name: php5.6-nginx_c
    volumes:
      - ./src:/var/www/
    ports:
      - "8085:80"
    depends_on:
      - mysql


  mysql:
    image: mysql:5.6
    container_name: mysql5.6_c
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_password
      MYSQL_ROOT_PASSWORD: docker_pass

 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_c
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql5.6_c
      MYSQL_ROOT_PASSWORD: docker_pass
    depends_on:
      - mysql






